name: Android Build

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ qa ]
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:

  #####################################################################################################################
  ## Build for Android
  #####################################################################################################################
  
  buildForAndroidPlatform:
    name: Build For Android Platform
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ./
        unityVersion:
          - 2020.3.15f2
        targetPlatform:
          - Android
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: false
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Restore LFS cache
        uses: actions/cache@v2.1.3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
      - name: Git LFS Pull
        run: git lfs pull
      - uses: actions/cache@v2.1.3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: game-ci/unity-builder@v2
        id: buildStep
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
          buildName: BlockBreaker
          allowDirtyBuild: true
      - uses: actions/upload-artifact@v2
        with:
          name: build-Android
          path: build/Android
          
  #####################################################################################################################
  ## App Distribution
  #####################################################################################################################
  
  appDistribution:
    name: Upload .apk file to Firebase
    runs-on: ubuntu-latest
    needs: buildForAndroidPlatform
    env:
      ANDROID_BUILD_FILE_PATH: ${{ format('{0}/build/Android/BlockBreaker.apk', github.workspace) }}
      FIREBASE_GROUP: test
      FIREBASE_RELEASE_NOTES: test222
    steps:
      - name: Test 1
        run: echo ${{github.workflow}}
      - name: Test 2
        run: echo ${{github.event}}
      - name: Test 3
        run: echo ${{github.actor}}
      - name: Test 4
        run: echo ${{github.run_number}}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Android Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-Android
          path: build/Android
      - uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          file: ${{env.ANDROID_BUILD_FILE_PATH}}
          groups: ${{env.FIREBASE_GROUP}}
          releaseNotes: ${{env.FIREBASE_RELEASE_NOTES}}
      
  #####################################################################################################################
  ## Final stuff
  #####################################################################################################################
  
  finalStuff:
    name: Do latest stuff after building
    runs-on: ubuntu-latest
    needs: appDistribution
    env:
      DISCORD_MESSAGE: ${{ format('{0}/build/Android/BlockBreaker.apk', github.workspace) }}
    steps:
      - name: Cleanup to avoid storage limit
        if: always()
        uses: geekyeggo/delete-artifact@v1
        with:
          name: build-Android
